server:
  port: ${PORT:8080}

spring:
  application:
    name: postService
  boot:
    admin:
      client:
        enabled: true
        url: http://microservice-monitoring:8080
        instance:
          service-url: http://microservice-post:8080

  liquibase:
    enabled: ${LIQ_ENABLE:false}
    drop-first: ${LIQ_DROP_FIRST:false}
    change-log: classpath:database-post-changelog.xml

  datasource:
    url: jdbc:${DATABASE_URL:postgresql://84.201.189.234:5432/postgres}
    username: ${USER_DB:postgres}
    password: ${PASS_DB:postgres}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: ${SCHEMA_DB:post}
    open-in-view: false

feign:
  service:
    url: ${URL_ACCOUNT:http://localhost:8081}
  friend:
    service:
      url: ${URL_FRIEND:http://localhost:8082}
  notification:
    service:
      url: ${URL_NOTIFICATION:http://localhost:8083}

final:
  title:
    length: ${TITLE_LENGHT:3}
  text:
    length: ${TEXT_LENGHT:5}
  default:
    date: -1

swagger:
  path: ${SWAGGER:http://localhost:8080}

cloudinary:
  url: ${CLOUDINARY_URL:cloudinary://134695888526851:KE9MgzsJisMn0B5izwBuXYK1Lsc@dhtldn8id}
